name: reveille
version: 0.0.0

category: Web
description: Reveille aggregates Haskell Weekly feeds.
extra-source-files:
  - CHANGELOG.markdown
  - CODE_OF_CONDUCT.markdown
  - package.yaml
  - README.markdown
  - stack.yaml
github: haskellweekly/reveille
license-file: LICENSE.markdown
license: MIT
maintainer: Taylor Fausak
synopsis: Aggregates Haskell Weekly feeds.

dependencies:
  async: '>= 2.1.1 && < 2.2'
  base: '>= 4.10.1 && < 4.11'
  bytestring: '>= 0.10.8 && < 0.11'
  clock: '>= 0.7.2 && < 0.8'
  connection: '>= 0.2.8 && < 0.3'
  containers: '>= 0.5.10 && < 0.6'
  feed: '>= 1.0.0 && < 1.1'
  http-client-tls: '>= 0.3.5 && < 0.4'
  http-client: '>= 0.5.7 && < 0.6'
  http-types: '>= 0.9.1 && < 0.10'
  network-uri: '>= 2.6.1 && < 2.7'
  stm: '>= 2.4.4 && < 2.5'
  text: '>= 1.2.2 && < 1.3'
  time: '>= 1.8.0 && < 1.9'
  transformers: '>= 0.5.2 && < 0.6'
  wai: '>= 3.2.1 && < 3.3'
  warp: '>= 3.2.13 && < 3.3'
  xml-conduit: '>= 1.7.0 && < 1.8'
ghc-options:
  - -Weverything
  - -Wno-implicit-prelude
  - -Wno-safe
  - -Wno-unsafe
  # https://github.com/haskell/cabal/issues/4739
  - -optP -Wno-nonportable-include-path

library:
  source-dirs: library

executable:
  dependencies:
    reveille: -any
  ghc-options:
    - -rtsopts
    - -threaded
  main: Main.hs
  source-dirs: executables

tests:
  test:
    dependencies:
      hspec: '>= 2.4.4 && < 2.5'
      reveille: -any
    ghc-options:
      - -rtsopts
      - -threaded
      - -Wno-missing-import-lists
    main: Main.hs
    source-dirs: tests
