name: reveille
version: 0.0.0

category: Web
description: Reveille aggregates Haskell Weekly feeds.
extra-source-files:
  - package.yaml
  - README.markdown
  - stack.yaml
github: haskellweekly/reveille
license-file: LICENSE.markdown
license: MIT
maintainer: Taylor Fausak
synopsis: Aggregates Haskell Weekly feeds.

executable:
  dependencies:
    async: '>= 2.1.1 && < 2.2'
    atom-conduit: '>= 0.5.0 && < 0.6'
    base: '>= 4.10.1 && < 4.11'
    bytestring: '>= 0.10.8 && < 0.11'
    conduit: '>= 1.3.0 && < 1.4'
    http-conduit: '>= 2.3.0 && < 2.4'
    http-types: '>= 0.12.1 && < 0.13'
    lucid: '>= 2.9.9 && < 2.10'
    mono-traversable: '>= 1.0.8 && < 1.1'
    rss-conduit: '>= 0.4.2 && < 0.5'
    sqlite-simple: '>= 0.4.14 && < 0.5'
    text: '>= 1.2.3 && < 1.3'
    time: '>= 1.8.0 && < 1.9'
    uri-bytestring: '>= 0.3.1 && < 0.4'
    wai: '>= 3.2.1 && < 3.3'
    warp: '>= 3.2.18 && < 3.3'
    xml-conduit: '>= 1.8.0 && < 1.9'
    xml-types: '>= 0.3.6 && < 0.4'
  ghc-options:
    - -optP -Wno-nonportable-include-path # https://github.com/haskell/cabal/issues/4739
    - -rtsopts
    - -threaded
    - -Weverything
    - -Wno-implicit-prelude
    - -Wno-safe
    - -Wno-unsafe
  main: reveille.hs
