name: aggie
version: 0.0.0

category: Web
description: Aggie aggregates Haskell Weekly feeds.
extra-source-files: README.markdown
github: tfausak/aggie
license-file: LICENSE.markdown
license: MIT
maintainer: Taylor Fausak
synopsis: Aggregates Haskell Weekly feeds.

executable:
  dependencies:
    - base >= 4.10.1 && < 4.11
    - containers >= 0.5.10 && < 0.6
    - feed >= 1.0.0 && < 1.1
    - http-client >= 0.5.7 && < 0.6
    - http-client-tls >= 0.3.5 && < 0.4
    - http-types >= 0.9.1 && < 0.10
    - stm >= 2.4.4 && < 2.5
    - text >= 1.2.2 && < 1.3
    - time >= 1.8.0 && < 1.9
    - wai >= 3.2.1 && < 3.3
    - warp >= 3.2.13 && < 3.3
    - xml-conduit >= 1.7.0 && < 1.8
  ghc-options:
    - -rtsopts
    - -threaded
    - -Weverything
    - -Wno-implicit-prelude
    - -Wno-safe
    - -Wno-unsafe
  main: aggie.hs
